# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}

  bench:
    cmds:
      - go test -bench=. -benchmem ./...

  generate:
    cmds:
      - go run ./scripts/main.go

  upgrade:
    cmds:
      - go get -u ./...
