# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  test:
    cmds:
      - go test ./...
  
  bench:
    cmds:
      - go test -bench=. ./... 
    
  generate:
    cmds:
      - go run ./scripts/main.go
  
  upgrade:
    cmds:
      - go get -u ./... 