name: Go
on:
  workflow_dispatch: ~
  pull_request: ~
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Install dependencies
        run: go get .

      - name: Run Tests
        run: go test -v ./...

      - name: Run Benchmarks
        run: go test -bench=. -benchmem ./...
